name: Build Ubuntu Image
on:
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        version:
#          - 16.04
          - 18.04
#          - 20.04
    steps:
    - uses: actions/checkout@v2
    - name: Set up QEMU
      uses: docker/setup-qemu-action@v1
    - name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v1
    - name: Login to GitHub Container Registry
      uses: docker/login-action@v1
      with:
        registry: ghcr.io
        username: ${{ github.actor }}
        password: ${{ secrets.CR_PAT }}
    - name: Login to DockerHub
      uses: docker/login-action@v1 
      with:
        username: ${{ secrets.DOCKERHUB_USERNAME }}
        password: ${{ secrets.DOCKERHUB_TOKEN }}
    - name: Build and Push
      id: docker_build
      uses: docker/build-push-action@v2
      with:
        context: .
        file: ./Dockerfile.ubuntu
        push: true
        build-args: |
            VERSION=${{ matrix.version }}
        tags: |
          ${{ github.repository_owner }}/baikal-dev:ubuntu-${{ matrix.version }}
          ghcr.io/${{ github.repository_owner }}/baikal-dev:ubuntu-${{ matrix.version }}
    
